### ISSUE TITLE
Training does not work properly and agent does not beyond first traffic light in TOWN02

### ISSUE THREAD

**Issue by DeLeonOscar** [idreesshaikh/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning#10]
Hello Idree, 

I was going through your code, and I had a question about a specific part of it. I was training a new agent from scratch in TOWN02. The training was going well (the average reward is increasing every timestep), however, out of a sudden at any point the training stopped and then “exit” is printed in the command window prompt. Basically, the training is not finished, and it does not get to the end of the training (the print “Terminating the run” does never appear). I run the training several times and still doing the same situation but at different timesteps. I am making sure that in the _while loop timestep < TOTAL_TIMESETPS,_ does not break because of this condition.  I have attached a screenshot of the situation when the training stops and jumps to the printed exit. I don’t know if run into a similar issue.

Another issue is that the agent does not go beyond the first traffic light corner. I run the code until 2M timesteps but every time the agent restart and stops in that specific point. I don't not if this issue is related to training is stopped unexpected.

Thank you, 
Oscar 
![Training_Stop](https://user-images.githubusercontent.com/108369351/234369565-66e3b107-90d9-4421-9b77-3f6b4e38740a.jpg)

**Comment by tqlblzj** [comment]
> Hello Idree,
> 
> I was going through your code, and I had a question about a specific part of it. I was training a new agent from scratch in TOWN02. The training was going well (the average reward is increasing every timestep), however, out of a sudden at any point the training stopped and then “exit” is printed in the command window prompt. Basically, the training is not finished, and it does not get to the end of the training (the print “Terminating the run” does never appear). I run the training several times and still doing the same situation but at different timesteps. I am making sure that in the _while loop timestep < TOTAL_TIMESETPS,_ does not break because of this condition. I have attached a screenshot of the situation when the training stops and jumps to the printed exit. I don’t know if run into a similar issue.
> 
> Another issue is that the agent does not go beyond the first traffic light corner. I run the code until 2M timesteps but every time the agent restart and stops in that specific point. I don't not if this issue is related to training is stopped unexpected.
> 
> Thank you, Oscar ![Training_Stop](https://user-images.githubusercontent.com/108369351/234369565-66e3b107-90d9-4421-9b77-3f6b4e38740a.jpg)
I think you have the same problem with me, what is your carla version? I trained it in town7 and it will exit in less than 150 eposides

**Comment by elpidak** [comment]
> Hello Idree,
> 
> I was going through your code, and I had a question about a specific part of it. I was training a new agent from scratch in TOWN02. The training was going well (the average reward is increasing every timestep), however, out of a sudden at any point the training stopped and then “exit” is printed in the command window prompt. Basically, the training is not finished, and it does not get to the end of the training (the print “Terminating the run” does never appear). I run the training several times and still doing the same situation but at different timesteps. I am making sure that in the _while loop timestep < TOTAL_TIMESETPS,_ does not break because of this condition. I have attached a screenshot of the situation when the training stops and jumps to the printed exit. I don’t know if run into a similar issue.
> 
> Another issue is that the agent does not go beyond the first traffic light corner. I run the code until 2M timesteps but every time the agent restart and stops in that specific point. I don't not if this issue is related to training is stopped unexpected.
> 
> Thank you, Oscar ![Training_Stop](https://user-images.githubusercontent.com/108369351/234369565-66e3b107-90d9-4421-9b77-3f6b4e38740a.jpg)

@DeLeonOscar Can I ask you something? With what parameters did you achive those results? Bacuse I am running it for a few days now with differenet experimentes but my rewards are keep getting increased in a much lower degree.
![image](https://github.com/idreesshaikh/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning/assets/72894021/2f04338f-5fad-4f77-85f5-be0afe4538dc)
