### ISSUE TITLE
There may be some errors in your code

### ISSUE THREAD

**Issue by GGGQAQ** [idreesshaikh/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning#12]
The 42nd line of code in the sensors.py file under the simulation folder,it seems like reshape((image.height, image.width, 4)) instead of reshape((image.width, iamge.height, 4)).If this error is true, your preTrained_models may need to be updated with the correct version.

**Comment by idreesshaikh** [comment]
Hi, it's preference of arrangement. You'd see similar differences in reshaping of a vector or tensor in different code examples. There's another file in the root of the directory called `encoder_init.py` where on line 24 you'd see that I'm using the permutation to rearrange them. Thanks a lot for highlighting this. 😊
