### ISSUE TITLE
How long training takes? 

### ISSUE THREAD

**Issue by DeLeonOscar** [idreesshaikh/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning#5]
Hello, 

I am currently training the PPO AV. I am using town 2 for the training process. However, the training does not seem to improve a lot every minute. It started in average reward 97. After 330 episodes, the average reward is  144. How long does it take to train a proper and safe AV? And how many episodes are required to complete a "full" training? 

Thank you,
-Oscar

**Comment by DeLeonOscar** [comment]
@idreesshaikh

**Comment by idreesshaikh** [comment]
Hi Oscar, I'd suggest to train the model for around (almost) 1000 episodes. You can refer to the `logs/ `directly to refer to the improvement in the score and all the other values. It takes around 8 hours to full train the model at least for me.
