### ISSUE TITLE
ValueError: Expected parameter loc (Tensor of shape (10516, 2)) of distribution MultivariateNormal(loc: torch.Size([10516, 2]), covariance_matrix: torch.Size([10516, 2, 2])) to satisfy the constraint IndependentConstraint(Real(), 1), but found invalid values: tensor([[nan, nan],         [nan, nan],         [nan, nan],         ...,         [nan, nan],         [nan, nan],         [nan, nan]], grad_fn=<ExpandBackward0>)

### ISSUE THREAD

**Issue by zengningjia** [idreesshaikh/Autonomous-Driving-in-Carla-using-Deep-Reinforcement-Learning#6]
![image](https://user-images.githubusercontent.com/51840867/223760944-9d3bf7ac-e953-4666-a34c-aa9b3e3ae0b9.png)
Hello, I met this bug when training a ppo agent in Town02. I can't fix it. 
Can u help me? Thanks a lot!

**Comment by idreesshaikh** [comment]
Well, what I understand from your error is that the algorithm didn't receive state input for it to process therefore it broke. I'd suggest to implement multi-threading to run simulation and algorithm consistently, or change it to a more powerful device.

**Comment by elpidak** [comment]
@zengningjia did you find a solution? I am facing the same issue
